version: '3.7'

services:
  database:
    container_name: database
    image: postgres
    networks:
      - auth-service_default
  web_1:
    build:
      context: .
    labels:
      apiRoute: '/api/v1/meals'
    container_name: meal-service
    # image: gcr.io/summer-hawk-258307/meals
    image: wagubib/microservice:meals
    volumes:
      - .:/usr/src/app
    ports:
      - "3071:3000"
    networks:
      - auth-service_default
    depends_on:
      - database
      - redis_1
    environment:
      APP_SETTINGS: "production"
      DATABASE_URL: "postgres://postgres:postgres@database/meal_db"
      REDIS_URL: redis://cache_1
      NODE_ENV: "docker"
  redis_1:
    image: 'redis:3.2.0'
    container_name: cache_1
    expose:
      - 6379
    networks:
      - auth-service_default
networks:
    auth-service_default:
      external: true
