version: '3.7'

services:
  db:
    image: postgres
    networks:
      - auth-service_default
  web:
    build:
      context: .
    labels:
      apiRoute: '/api/v1/meals'
    container_name: meal-service
    volumes:
      - .:/usr/src/app
    ports:
      - "3071:3000"
    networks:
      - auth-service_default
    depends_on:
      - db
      - redis
    environment:
      APP_SETTINGS: "production"
      DATABASE_URL: "postgres://postgres:postgres@db/meal_db"
      REDIS_URL: redis://cache_1
      NODE_ENV: "docker"
  redis:
    image: 'redis:3.2.0'
    container_name: cache_1
    expose:
      - 6379
    networks:
      - auth-service_default
networks:
    auth-service_default:
      external: true
