apiVersion: v1
kind: Service
metadata:
  annotations:
    apiRoute: /api/v1/meals
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web-1
  name: web-1
spec:
  ports:
  - name: "3071"
    port: 3071
    targetPort: 3000
  selector:
    io.kompose.service: web-1
  # type: LoadBalancer
status:
  loadBalancer: {}
